CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

CREATE TABLE IF NOT EXISTS public.situacao_cadastros (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  descricao VARCHAR(150) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(150) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.fin_contabilidades (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  descricao VARCHAR(150) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.tipo_conselho_profissional (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  descricao VARCHAR(150) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.solicitantes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(150) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.solicitante_cbo (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  descricao VARCHAR(150) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.configuracao_solicitantes_estados (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  descricao VARCHAR(150) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.medico_responsaveis_tipo_cadastro (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  descricao VARCHAR(150) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.homecare_escala_repasse_tabela_padrao (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  descricao VARCHAR(150) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.estado_civis (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  descricao VARCHAR(150) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.religiao (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  descricao VARCHAR(150) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.etnia (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  descricao VARCHAR(150) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.escolaridade (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  descricao VARCHAR(150) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.home_care_regiao_responsavel (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  descricao VARCHAR(150) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.configuracao_apuracao (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  descricao VARCHAR(150) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.fin_fornecedores (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(150) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.fin_plano_contas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  descricao VARCHAR(150) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.unidades (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(150) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.medico_responsaveis (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(150) NOT NULL,
  cpf VARCHAR(14) NOT NULL,
  crm VARCHAR(50) NOT NULL,
  situacao_id BIGINT NOT NULL REFERENCES public.situacao_cadastros(id),
  user_id BIGINT REFERENCES public.users(id),
  produtividade_fin_contabilidade_id BIGINT REFERENCES public.fin_contabilidades(id),
  id_tipo_conselho_profissional BIGINT NOT NULL REFERENCES public.tipo_conselho_profissional(id),
  solicitante_id BIGINT REFERENCES public.solicitantes(id),
  cbo_id BIGINT REFERENCES public.solicitante_cbo(id),
  estado_id BIGINT REFERENCES public.configuracao_solicitantes_estados(id),
  tipo_cadastro_id BIGINT REFERENCES public.medico_responsaveis_tipo_cadastro(id),
  homecare_escala_repasse_tabela_padrao_id BIGINT REFERENCES public.homecare_escala_repasse_tabela_padrao(id),
  estado_civil_id BIGINT REFERENCES public.estado_civis(id),
  religiao_id BIGINT REFERENCES public.religiao(id),
  etnia_id BIGINT REFERENCES public.etnia(id),
  escolaridade_id BIGINT REFERENCES public.escolaridade(id),
  home_care_regiao_responsavel_id BIGINT REFERENCES public.home_care_regiao_responsavel(id),
  configuracao_apuracao_id BIGINT REFERENCES public.configuracao_apuracao(id),
  fin_fornecedor_id BIGINT REFERENCES public.fin_fornecedores(id),
  contas_pagar_plano_contas_id BIGINT REFERENCES public.fin_plano_contas(id),
  contas_receber_plano_contas_id BIGINT REFERENCES public.fin_plano_contas(id),
  unidade_id BIGINT NOT NULL REFERENCES public.unidades(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.medico_responsaveis_cbo (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  medico_responsaveis_id BIGINT NOT NULL REFERENCES public.medico_responsaveis(id) ON DELETE CASCADE,
  cbo_id BIGINT NOT NULL REFERENCES public.solicitante_cbo(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (medico_responsaveis_id, cbo_id)
);

CREATE TABLE IF NOT EXISTS public.medico_responsaveis_sus_exportacao (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  medico_responsaveis_id BIGINT NOT NULL REFERENCES public.medico_responsaveis(id) ON DELETE CASCADE,
  data_exportacao TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_medico_responsaveis_nome ON public.medico_responsaveis(nome);
CREATE INDEX IF NOT EXISTS idx_medico_responsaveis_cpf ON public.medico_responsaveis(cpf);
CREATE INDEX IF NOT EXISTS idx_medico_responsaveis_crm ON public.medico_responsaveis(crm);
CREATE INDEX IF NOT EXISTS idx_medico_responsaveis_situacao_id ON public.medico_responsaveis(situacao_id);
CREATE INDEX IF NOT EXISTS idx_medico_responsaveis_tipo_conselho ON public.medico_responsaveis(id_tipo_conselho_profissional);
CREATE INDEX IF NOT EXISTS idx_medico_responsaveis_unidade_id ON public.medico_responsaveis(unidade_id);
CREATE INDEX IF NOT EXISTS idx_medico_responsaveis_solicitante_id ON public.medico_responsaveis(solicitante_id);
CREATE INDEX IF NOT EXISTS idx_medico_responsaveis_cbo_medico ON public.medico_responsaveis_cbo(medico_responsaveis_id);
CREATE INDEX IF NOT EXISTS idx_medico_responsaveis_sus_exportacao_medico ON public.medico_responsaveis_sus_exportacao(medico_responsaveis_id);

DROP TRIGGER IF EXISTS update_medico_responsaveis_updated_at ON public.medico_responsaveis;
CREATE TRIGGER update_medico_responsaveis_updated_at
BEFORE UPDATE ON public.medico_responsaveis
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();

ALTER TABLE public.situacao_cadastros ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fin_contabilidades ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tipo_conselho_profissional ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.solicitantes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.solicitante_cbo ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.configuracao_solicitantes_estados ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.medico_responsaveis_tipo_cadastro ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.homecare_escala_repasse_tabela_padrao ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.estado_civis ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.religiao ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.etnia ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.escolaridade ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.home_care_regiao_responsavel ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.configuracao_apuracao ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fin_fornecedores ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fin_plano_contas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.unidades ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.medico_responsaveis ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.medico_responsaveis_cbo ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.medico_responsaveis_sus_exportacao ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can manage situacao_cadastros"
ON public.situacao_cadastros
FOR ALL
TO authenticated
USING (true)
WITH CHECK (true);

CREATE POLICY "Authenticated users can manage users"
ON public.users
FOR ALL
TO authenticated
USING (true)
WITH CHECK (true);

CREATE POLICY "Authenticated users can manage fin_contabilidades"
ON public.fin_contabilidades
FOR ALL
TO authenticated
USING (true)
WITH CHECK (true);

CREATE POLICY "Authenticated users can manage tipo_conselho_profissional"
ON public.tipo_conselho_profissional
FOR ALL
TO authenticated
USING (true)
WITH CHECK (true);

CREATE POLICY "Authenticated users can manage solicitantes"
ON public.solicitantes
FOR ALL
TO authenticated
USING (true)
WITH CHECK (true);

CREATE POLICY "Authenticated users can manage solicitante_cbo"
ON public.solicitante_cbo
FOR ALL
TO authenticated
USING (true)
WITH CHECK (true);

CREATE POLICY "Authenticated users can manage configuracao_solicitantes_estados"
ON public.configuracao_solicitantes_estados
FOR ALL
TO authenticated
USING (true)
WITH CHECK (true);

CREATE POLICY "Authenticated users can manage medico_responsaveis_tipo_cadastro"
ON public.medico_responsaveis_tipo_cadastro
FOR ALL
TO authenticated
USING (true)
WITH CHECK (true);

CREATE POLICY "Authenticated users can manage homecare_escala_repasse_tabela_padrao"
ON public.homecare_escala_repasse_tabela_padrao
FOR ALL
TO authenticated
USING (true)
WITH CHECK (true);

CREATE POLICY "Authenticated users can manage estado_civis"
ON public.estado_civis
FOR ALL
TO authenticated
USING (true)
WITH CHECK (true);

CREATE POLICY "Authenticated users can manage religiao"
ON public.religiao
FOR ALL
TO authenticated
USING (true)
WITH CHECK (true);

CREATE POLICY "Authenticated users can manage etnia"
ON public.etnia
FOR ALL
TO authenticated
USING (true)
WITH CHECK (true);

CREATE POLICY "Authenticated users can manage escolaridade"
ON public.escolaridade
FOR ALL
TO authenticated
USING (true)
WITH CHECK (true);

CREATE POLICY "Authenticated users can manage home_care_regiao_responsavel"
ON public.home_care_regiao_responsavel
FOR ALL
TO authenticated
USING (true)
WITH CHECK (true);

CREATE POLICY "Authenticated users can manage configuracao_apuracao"
ON public.configuracao_apuracao
FOR ALL
TO authenticated
USING (true)
WITH CHECK (true);

CREATE POLICY "Authenticated users can manage fin_fornecedores"
ON public.fin_fornecedores
FOR ALL
TO authenticated
USING (true)
WITH CHECK (true);

CREATE POLICY "Authenticated users can manage fin_plano_contas"
ON public.fin_plano_contas
FOR ALL
TO authenticated
USING (true)
WITH CHECK (true);

CREATE POLICY "Authenticated users can manage unidades"
ON public.unidades
FOR ALL
TO authenticated
USING (true)
WITH CHECK (true);

CREATE POLICY "Authenticated users can manage medico_responsaveis"
ON public.medico_responsaveis
FOR ALL
TO authenticated
USING (true)
WITH CHECK (true);

CREATE POLICY "Authenticated users can manage medico_responsaveis_cbo"
ON public.medico_responsaveis_cbo
FOR ALL
TO authenticated
USING (true)
WITH CHECK (true);

CREATE POLICY "Authenticated users can manage medico_responsaveis_sus_exportacao"
ON public.medico_responsaveis_sus_exportacao
FOR ALL
TO authenticated
USING (true)
WITH CHECK (true);

INSERT INTO public.situacao_cadastros (id, descricao)
VALUES (1, 'Ativo'), (2, 'Inativo')
ON CONFLICT (id) DO UPDATE SET descricao = EXCLUDED.descricao;

INSERT INTO public.tipo_conselho_profissional (id, descricao)
VALUES (1, 'CRM'), (2, 'COREN'), (3, 'CREFITO'), (4, 'CRP'), (5, 'Outro')
ON CONFLICT (id) DO UPDATE SET descricao = EXCLUDED.descricao;

INSERT INTO public.medico_responsaveis_tipo_cadastro (id, descricao)
VALUES (1, 'Médico'), (2, 'Enfermeiro'), (3, 'Fisioterapeuta'), (4, 'Psicólogo'), (5, 'Outro')
ON CONFLICT (id) DO UPDATE SET descricao = EXCLUDED.descricao;

INSERT INTO public.estado_civis (id, descricao)
VALUES (1, 'Solteiro'), (2, 'Casado'), (3, 'Divorciado'), (4, 'Viúvo')
ON CONFLICT (id) DO UPDATE SET descricao = EXCLUDED.descricao;

INSERT INTO public.religiao (id, descricao)
VALUES (1, 'Não informado')
ON CONFLICT (id) DO UPDATE SET descricao = EXCLUDED.descricao;

INSERT INTO public.etnia (id, descricao)
VALUES (1, 'Não informado')
ON CONFLICT (id) DO UPDATE SET descricao = EXCLUDED.descricao;

INSERT INTO public.escolaridade (id, descricao)
VALUES (1, 'Não informado')
ON CONFLICT (id) DO UPDATE SET descricao = EXCLUDED.descricao;

INSERT INTO public.configuracao_solicitantes_estados (id, descricao)
VALUES (1, 'MS'), (2, 'MT'), (3, 'GO'), (4, 'SP'), (5, 'PR')
ON CONFLICT (id) DO UPDATE SET descricao = EXCLUDED.descricao;

INSERT INTO public.unidades (id, nome)
VALUES (1, 'Unidade Principal')
ON CONFLICT (id) DO UPDATE SET nome = EXCLUDED.nome;

INSERT INTO public.fin_plano_contas (id, descricao)
VALUES (1, 'Plano de Contas Padrão')
ON CONFLICT (id) DO UPDATE SET descricao = EXCLUDED.descricao;

INSERT INTO public.fin_contabilidades (id, descricao)
VALUES (1, 'Contabilidade Padrão')
ON CONFLICT (id) DO UPDATE SET descricao = EXCLUDED.descricao;

INSERT INTO public.configuracao_apuracao (id, descricao)
VALUES (1, 'Apuração Padrão')
ON CONFLICT (id) DO UPDATE SET descricao = EXCLUDED.descricao;

INSERT INTO public.homecare_escala_repasse_tabela_padrao (id, descricao)
VALUES (1, 'Tabela Padrão')
ON CONFLICT (id) DO UPDATE SET descricao = EXCLUDED.descricao;

INSERT INTO public.home_care_regiao_responsavel (id, descricao)
VALUES (1, 'Região Principal')
ON CONFLICT (id) DO UPDATE SET descricao = EXCLUDED.descricao;

INSERT INTO public.fin_fornecedores (id, nome)
VALUES (1, 'Fornecedor Padrão')
ON CONFLICT (id) DO UPDATE SET nome = EXCLUDED.nome;

INSERT INTO public.solicitante_cbo (id, descricao)
VALUES (1, 'Médico Clínico'), (2, 'Enfermeiro'), (3, 'Fisioterapeuta')
ON CONFLICT (id) DO UPDATE SET descricao = EXCLUDED.descricao;

INSERT INTO public.solicitantes (id, nome)
VALUES (1, 'Solicitante Padrão')
ON CONFLICT (id) DO UPDATE SET nome = EXCLUDED.nome;

INSERT INTO public.users (id, nome)
VALUES (1, 'Administrador')
ON CONFLICT (id) DO UPDATE SET nome = EXCLUDED.nome;

SELECT setval(pg_get_serial_sequence('public.situacao_cadastros', 'id'), COALESCE((SELECT MAX(id) FROM public.situacao_cadastros), 1), true);
SELECT setval(pg_get_serial_sequence('public.users', 'id'), COALESCE((SELECT MAX(id) FROM public.users), 1), true);
SELECT setval(pg_get_serial_sequence('public.fin_contabilidades', 'id'), COALESCE((SELECT MAX(id) FROM public.fin_contabilidades), 1), true);
SELECT setval(pg_get_serial_sequence('public.tipo_conselho_profissional', 'id'), COALESCE((SELECT MAX(id) FROM public.tipo_conselho_profissional), 1), true);
SELECT setval(pg_get_serial_sequence('public.solicitantes', 'id'), COALESCE((SELECT MAX(id) FROM public.solicitantes), 1), true);
SELECT setval(pg_get_serial_sequence('public.solicitante_cbo', 'id'), COALESCE((SELECT MAX(id) FROM public.solicitante_cbo), 1), true);
SELECT setval(pg_get_serial_sequence('public.configuracao_solicitantes_estados', 'id'), COALESCE((SELECT MAX(id) FROM public.configuracao_solicitantes_estados), 1), true);
SELECT setval(pg_get_serial_sequence('public.medico_responsaveis_tipo_cadastro', 'id'), COALESCE((SELECT MAX(id) FROM public.medico_responsaveis_tipo_cadastro), 1), true);
SELECT setval(pg_get_serial_sequence('public.homecare_escala_repasse_tabela_padrao', 'id'), COALESCE((SELECT MAX(id) FROM public.homecare_escala_repasse_tabela_padrao), 1), true);
SELECT setval(pg_get_serial_sequence('public.estado_civis', 'id'), COALESCE((SELECT MAX(id) FROM public.estado_civis), 1), true);
SELECT setval(pg_get_serial_sequence('public.religiao', 'id'), COALESCE((SELECT MAX(id) FROM public.religiao), 1), true);
SELECT setval(pg_get_serial_sequence('public.etnia', 'id'), COALESCE((SELECT MAX(id) FROM public.etnia), 1), true);
SELECT setval(pg_get_serial_sequence('public.escolaridade', 'id'), COALESCE((SELECT MAX(id) FROM public.escolaridade), 1), true);
SELECT setval(pg_get_serial_sequence('public.home_care_regiao_responsavel', 'id'), COALESCE((SELECT MAX(id) FROM public.home_care_regiao_responsavel), 1), true);
SELECT setval(pg_get_serial_sequence('public.configuracao_apuracao', 'id'), COALESCE((SELECT MAX(id) FROM public.configuracao_apuracao), 1), true);
SELECT setval(pg_get_serial_sequence('public.fin_fornecedores', 'id'), COALESCE((SELECT MAX(id) FROM public.fin_fornecedores), 1), true);
SELECT setval(pg_get_serial_sequence('public.fin_plano_contas', 'id'), COALESCE((SELECT MAX(id) FROM public.fin_plano_contas), 1), true);
SELECT setval(pg_get_serial_sequence('public.unidades', 'id'), COALESCE((SELECT MAX(id) FROM public.unidades), 1), true);